[general]
live_config_reload=true

[colors.bright]
black = "0x666666"
blue = "0x7aa6da"
cyan = "0x54ced0"
green = "0x9ec400"
magenta = "0xb77ee0"
red = "0xff3334"
white = "0xffffff"
yellow = "0xe7c547"

[colors.normal]
black = "0x000000"
blue = "0x7aa6da"
cyan = "0x70c0c0"
green = "0xb9ca4a"
magenta = "0xc397d8"
red = "0xd54e53"
white = "0xeaeaea"
yellow = "0xe6c547"

[colors.primary]
background = "0x000000"
foreground = "0xcacaca"

[cursor]
style = "Block"
unfocused_hollow = true


[font]
size = 11

[font.bold]
family = "Inconsolata LGC Nerd Font Mono"
style = "Bold"

[font.normal]
family = "Inconsolata LGC Nerd Font Mono"

[font.italic]
family = "Inconsolata LGC Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "Inconsolata LGC Nerd Font Mono"
style = "Bold Italic"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.9


